repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13  # atau versi terbaru, cek https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff-format
        args: ["--check"]
      - id: ruff
        name: ruff-lint
        args: ["."]

# Opsional: auto-update pre-commit (best practice CI)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
